In [1]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

Using TensorFlow backend.


In [2]:
corpus = [
    # Positive Reviews

    'This is an excellent movie',
    'The move was fantastic I like it',
    'You should watch it is brilliant',
    'Exceptionally good',
    'Wonderfully directed and executed I like it',
    'Its a fantastic series',
    'Never watched such a brillent movie',
    'It is a Wonderful movie',

    # Negtive Reviews

    "horrible acting",
    'waste of money',
    'pathetic picture',
    'It was very boring',
    'I did not like the movie',
    'The movie was horrible',
    'I will not recommend',
    'The acting is pathetic'
]

In [3]:
sentiments = array([1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0])

In [4]:
from nltk.tokenize import word_tokenize

all_words = []
for sent in corpus:
    tokenize_word = word_tokenize(sent)
    for word in tokenize_word:
        all_words.append(word)
print(all_words)

['This', 'is', 'an', 'excellent', 'movie', 'The', 'move', 'was', 'fantastic', 'I', 'like', 'it', 'You', 'should', 'watch', 'it', 'is', 'brilliant', 'Exceptionally', 'good', 'Wonderfully', 'directed', 'and', 'executed', 'I', 'like', 'it', 'Its', 'a', 'fantastic', 'series', 'Never', 'watched', 'such', 'a', 'brillent', 'movie', 'It', 'is', 'a', 'Wonderful', 'movie', 'horrible', 'acting', 'waste', 'of', 'money', 'pathetic', 'picture', 'It', 'was', 'very', 'boring', 'I', 'did', 'not', 'like', 'the', 'movie', 'The', 'movie', 'was', 'horrible', 'I', 'will', 'not', 'recommend', 'The', 'acting', 'is', 'pathetic']


In [5]:
unique_words = set(all_words)
print(len(unique_words))
print(len(all_words))

45
71


In [6]:
vocab_length = 50
embedded_sentences = [one_hot(sent, vocab_length) for sent in corpus]
print(embedded_sentences )

[[7, 31, 43, 17, 25], [4, 48, 24, 20, 10, 48, 31], [23, 4, 45, 31, 31, 12], [4, 7], [39, 28, 4, 41, 10, 48, 31], [5, 42, 20, 21], [8, 14, 45, 42, 45, 25], [31, 31, 42, 13, 25], [35, 27], [5, 45, 28], [42, 38], [31, 24, 43, 9], [10, 46, 7, 48, 4, 25], [4, 25, 24, 35], [10, 5, 7, 45], [4, 27, 31, 42]]


In [7]:
max_sentence_size = max(list(map(lambda sentence : len(word_tokenize(sentence)), corpus)))
print(max_sentence_size)

7


In [8]:
padded_sentences = pad_sequences(embedded_sentences, max_sentence_size, padding='post')
print(padded_sentences)

[[ 7 31 43 17 25  0  0]
 [ 4 48 24 20 10 48 31]
 [23  4 45 31 31 12  0]
 [ 4  7  0  0  0  0  0]
 [39 28  4 41 10 48 31]
 [ 5 42 20 21  0  0  0]
 [ 8 14 45 42 45 25  0]
 [31 31 42 13 25  0  0]
 [35 27  0  0  0  0  0]
 [ 5 45 28  0  0  0  0]
 [42 38  0  0  0  0  0]
 [31 24 43  9  0  0  0]
 [10 46  7 48  4 25  0]
 [ 4 25 24 35  0  0  0]
 [10  5  7 45  0  0  0]
 [ 4 27 31 42  0  0  0]]


In [9]:
model = Sequential()
model.add(Embedding(vocab_length, 20, input_length=max_sentence_size))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [10]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 7, 20)             1000      
_________________________________________________________________
flatten_1 (Flatten)          (None, 140)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 141       
Total params: 1,141
Trainable params: 1,141
Non-trainable params: 0
_________________________________________________________________
None


In [9]:
train_sentences = padded_sentences[:-1]
test_sentences = padded_sentences[-1]
train_sentiments = sentiments[:-1]
test_sentiments = sentiments[-1]

In [12]:
model.fit(train_sentences, train_sentiments, epochs=100, verbose=1)

C:\Users\33777\Anaconda3\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/100
15/15 [==============================] - 0s 12ms/step - loss: 0.6898 - acc: 0.5333
Epoch 2/100
15/15 [==============================] - 0s 134us/step - loss: 0.6865 - acc: 0.7333
Epoch 3/100
15/15 [==============================] - 0s 133us/step - loss: 0.6831 - acc: 0.7333
Epoch 4/100
15/15 [==============================] - 0s 200us/step - loss: 0.6798 - acc: 0.8000
Epoch 5/100
15/15 [==============================] - 0s 200us/step - loss: 0.6765 - acc: 0.8000
Epoch 6/100
15/15 [==============================] - 0s 200us/step - loss: 0.6732 - acc: 0.9333
Epoch 7/100
15/15 [==============================] - 0s 200us/step - loss: 0.6699 - acc: 0.9333
Epoch 8/100
15/15 [==============================] - 0s 199us/step - loss: 0.6666 - acc: 0.9333
Epoch 9/100
15/15 [==============================] - 0s 200us/step - loss: 0.6633 - acc: 0.9333
Epoch 10/100
15/15 [==============================] - 0s 200us/step - loss: 0.6600 - acc: 0.9333
Epoch 11/100
15/15 [====================

Epoch 86/100
15/15 [==============================] - 0s 200us/step - loss: 0.3407 - acc: 1.0000
Epoch 87/100
15/15 [==============================] - 0s 133us/step - loss: 0.3364 - acc: 1.0000
Epoch 88/100
15/15 [==============================] - 0s 200us/step - loss: 0.3321 - acc: 1.0000
Epoch 89/100
15/15 [==============================] - 0s 133us/step - loss: 0.3278 - acc: 1.0000
Epoch 90/100
15/15 [==============================] - 0s 201us/step - loss: 0.3236 - acc: 1.0000
Epoch 91/100
15/15 [==============================] - 0s 200us/step - loss: 0.3194 - acc: 1.0000
Epoch 92/100
15/15 [==============================] - 0s 133us/step - loss: 0.3153 - acc: 1.0000
Epoch 93/100
15/15 [==============================] - 0s 200us/step - loss: 0.3112 - acc: 1.0000
Epoch 94/100
15/15 [==============================] - 0s 266us/step - loss: 0.3071 - acc: 1.0000
Epoch 95/100
15/15 [==============================] - 0s 133us/step - loss: 0.3030 - acc: 1.0000
Epoch 96/100
15/15 [==========

In [14]:
loss, accuracy = model.evaluate(train_sentences, train_sentiments, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000


In [16]:
a = array([test_sentences])
a

array([[37,  7, 36, 10,  0,  0,  0]])

In [20]:
predictions = model.predict(a)
rounded = [round(x[0]) for x in predictions]
rounded

[0.0]

###  ============================  Other Text ============================ 

In [28]:
import pandas as pd
import numpy as np

df = pd.read_csv('imdb_labelled.txt', delimiter = '\t', engine='python', quoting = 3)
df.head(5)

Review  Status
0  A very, very, very slow-moving, aimless movie ...       0
1  Not sure who was more lost - the flat characte...       0
2  Attempting artiness with black & white and cle...       0
3       Very little music or anything to speak of.         0
4  The best scene in the movie was when Gerardo i...       1

In [35]:
text = df["Review"]
labels = df["Status"]

In [36]:
from nltk.tokenize import word_tokenize
all_words = []

for sentence in text:
    words = word_tokenize(sentence)
    for word in words:
        all_words.append(word)

In [40]:
unique_words = set(all_words)
print(len(all_words))
print(len(unique_words))

16645
3421


In [43]:
vocab_length = 3430
coded_sentences = [one_hot(sentence, vocab_length) for sentence in text]
print(coded_sentences[0:5])

[[654, 710, 710, 710, 941, 1125, 2270, 3314, 1612, 654, 1365, 2314, 2832, 2558], [953, 970, 1967, 135, 2593, 1708, 2475, 1319, 3282, 1973, 2475, 1985, 2117, 3247, 898, 1807, 452, 254], [1387, 3197, 1513, 1079, 288, 891, 2517, 1565, 2374, 2475, 3314, 2152, 1546, 1116, 2593, 792, 324, 2475, 1322, 135, 3313, 891, 2475, 2005, 891, 2598, 1858, 2997, 2103], [710, 2441, 1660, 1973, 2246, 3304, 1671, 898], [2475, 1107, 2093, 3037, 2475, 3314, 135, 945, 335, 1482, 1129, 3304, 389, 654, 657, 3352, 327, 1992, 3276, 1843, 2675]]


In [45]:
max_sentence_size = max(list(map(lambda sentence : len(word_tokenize(sentence)), text)))
print(max_sentence_size)

80


In [47]:
padded_sentences = pad_sequences(coded_sentences, max_sentence_size, padding='post')
print(padded_sentences)

[[ 654  710  710 ...    0    0    0]
 [ 953  970 1967 ...    0    0    0]
 [1387 3197 1513 ...    0    0    0]
 ...
 [3037  654 2638 ...    0    0    0]
 [1297 1147    0 ...    0    0    0]
 [2504 3037 2504 ...    0    0    0]]


In [10]:
def getModel(texts_train, labels_train):
    model = Sequential()
    model.add(Embedding(vocab_length, 20, input_length=max_sentence_size))
    model.add(Flatten())
    model.add(Dense(1, activation='sigmoid'))
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
    model.fit(train_sentences, train_sentiments, epochs=100, verbose=1)
    loss, accuracy = model.evaluate(train_sentences, train_sentiments, verbose=0)
    print('Accuracy: %f' % (accuracy*100))
    return model

In [12]:
model = getModel(texts_train= train_sentences, labels_train = train_sentiments)

C:\Users\33777\Anaconda3\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/100
15/15 [==============================] - 0s 19ms/step - loss: 0.6871 - acc: 0.6000
Epoch 2/100
15/15 [==============================] - 0s 132us/step - loss: 0.6839 - acc: 0.6667
Epoch 3/100
15/15 [==============================] - 0s 200us/step - loss: 0.6807 - acc: 0.7333
Epoch 4/100
15/15 [==============================] - 0s 268us/step - loss: 0.6775 - acc: 0.8000
Epoch 5/100
15/15 [==============================] - 0s 200us/step - loss: 0.6743 - acc: 0.8667
Epoch 6/100
15/15 [==============================] - 0s 200us/step - loss: 0.6712 - acc: 0.8667
Epoch 7/100
15/15 [==============================] - 0s 200us/step - loss: 0.6680 - acc: 0.9333
Epoch 8/100
15/15 [==============================] - 0s 333us/step - loss: 0.6649 - acc: 0.9333
Epoch 9/100
15/15 [==============================] - 0s 200us/step - loss: 0.6618 - acc: 0.9333
Epoch 10/100
15/15 [==============================] - 0s 335us/step - loss: 0.6586 - acc: 0.9333
Epoch 11/100
15/15 [====================

Epoch 86/100
15/15 [==============================] - 0s 200us/step - loss: 0.3614 - acc: 0.9333
Epoch 87/100
15/15 [==============================] - 0s 200us/step - loss: 0.3574 - acc: 0.9333
Epoch 88/100
15/15 [==============================] - 0s 200us/step - loss: 0.3533 - acc: 0.9333
Epoch 89/100
15/15 [==============================] - 0s 304us/step - loss: 0.3493 - acc: 0.9333
Epoch 90/100
15/15 [==============================] - 0s 200us/step - loss: 0.3453 - acc: 0.9333
Epoch 91/100
15/15 [==============================] - 0s 200us/step - loss: 0.3414 - acc: 0.9333
Epoch 92/100
15/15 [==============================] - 0s 200us/step - loss: 0.3375 - acc: 0.9333
Epoch 93/100
15/15 [==============================] - 0s 200us/step - loss: 0.3336 - acc: 0.9333
Epoch 94/100
15/15 [==============================] - 0s 200us/step - loss: 0.3297 - acc: 0.9333
Epoch 95/100
15/15 [==============================] - 0s 200us/step - loss: 0.3259 - acc: 0.9333
Epoch 96/100
15/15 [==========

In [1]:
predictions = model.predict(array([test_sentences]))
rounded = [round(x[0]) for x in predictions]
rounded

NameError: name 'model' is not defined

In [2]:
def test():
    print("test export")